config/routes.rb
Rails.application.routes.draw do
  resources :tasks_labels
  resources :labels
  root "sessions#new"
  resources :tasks
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  namespace :admin do
    resources :users
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tasks_label.rb
class TasksLabel < ApplicationRecord
  belongs_to :label
  belongs_to :task
end

app/controllers/tasks_labels_controller.rb
class TasksLabelsController < ApplicationController
  before_action :set_tasks_label, only: [:show, :edit, :update, :destroy]

  # GET /tasks_labels
  # GET /tasks_labels.json
  def index
    @tasks_labels = TasksLabel.all
  end

  # GET /tasks_labels/1
  # GET /tasks_labels/1.json
  def show
  end

  # GET /tasks_labels/new
  def new
    @tasks_label = TasksLabel.new
  end

  # GET /tasks_labels/1/edit
  def edit
  end

  # POST /tasks_labels
  # POST /tasks_labels.json
  def create
    @tasks_label = TasksLabel.new(tasks_label_params)

    respond_to do |format|
      if @tasks_label.save
        format.html { redirect_to @tasks_label, notice: 'Tasks label was successfully created.' }
        format.json { render :show, status: :created, location: @tasks_label }
      else
        format.html { render :new }
        format.json { render json: @tasks_label.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks_labels/1
  # PATCH/PUT /tasks_labels/1.json
  def update
    respond_to do |format|
      if @tasks_label.update(tasks_label_params)
        format.html { redirect_to @tasks_label, notice: 'Tasks label was successfully updated.' }
        format.json { render :show, status: :ok, location: @tasks_label }
      else
        format.html { render :edit }
        format.json { render json: @tasks_label.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks_labels/1
  # DELETE /tasks_labels/1.json
  def destroy
    @tasks_label.destroy
    respond_to do |format|
      format.html { redirect_to tasks_labels_url, notice: 'Tasks label was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tasks_label
      @tasks_label = TasksLabel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tasks_label_params
      params.require(:tasks_label).permit(:label_id, :task_id)
    end
end

app/helpers/tasks_labels_helper.rb
module TasksLabelsHelper
end

app/views/tasks_labels/_form.html.erb
<%= form_with(model: tasks_label, local: true) do |form| %>
  <% if tasks_label.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tasks_label.errors.count, "error") %> prohibited this tasks_label from being saved:</h2>

      <ul>
      <% tasks_label.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :label_id %>
    <%= form.text_field :label_id %>
  </div>

  <div class="field">
    <%= form.label :task_id %>
    <%= form.text_field :task_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks_labels/edit.html.erb
<h3>Editing Tasks Label</h3>

<%= render 'form', tasks_label: @tasks_label %>

<%= link_to 'Show', @tasks_label %> |
<%= link_to 'Back', tasks_labels_path %>

app/views/tasks_labels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tasks Labels</h1>

<table>
  <thead>
    <tr>
      <th>Label</th>
      <th>Task</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks_labels.each do |tasks_label| %>
      <tr>
        <td><%= tasks_label.label %></td>
        <td><%= tasks_label.task %></td>
        <td><%= link_to 'Show', tasks_label %></td>
        <td><%= link_to 'Edit', edit_tasks_label_path(tasks_label) %></td>
        <td><%= link_to 'Destroy', tasks_label, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tasks Label', new_tasks_label_path %>

app/views/tasks_labels/new.html.erb
<h1>New Tasks Label</h1>

<%= render 'form', tasks_label: @tasks_label %>

<%= link_to 'Back', tasks_labels_path %>

app/views/tasks_labels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Label:</strong>
  <%= @tasks_label.label %>
</p>

<p>
  <strong>Task:</strong>
  <%= @tasks_label.task %>
</p>

<%= link_to 'Edit', edit_tasks_label_path(@tasks_label) %> |
<%= link_to 'Back', tasks_labels_path %>