config/routes.rb
Rails.application.routes.draw do
  resources :tasks_labels
  resources :labels
  root "sessions#new"
  resources :tasks
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  namespace :admin do
    resources :users
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/task.rb
class Task < ApplicationRecord
    belongs_to :user
    validates :title, :content, presence:true
    validates :content, presence:true 
    validates :start_date, presence:true
    validates :end_date, presence:true
    enum priority: [:low,:medium,:high]
    paginates_per 10
    has_many :tasks_labels, dependent: :destroy
    has_many :labels, :through => :tasks_labels, dependent: :destroy
    accepts_nested_attributes_for :tasks_labels, :reject_if => proc { |a|
    a['label_id'].blank? }
    accepts_nested_attributes_for :labels  
    def self.search(search)
        Task.joins(:labels).where("labels.title LIKE ?", "%#{search}%")
    end 
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
    
  def index
    @search = Task.ransack(params[:q])
    if params[:q]
      @tasks = @search.result.page(params[:page])
    elsif params[:sort_with_priority]
      @tasks = Task.order('priority DESC').page(params[:page])
    elsif params[:sort_with_ended_at]
      @tasks = Task.order('end_date DESC').page(params[:page])
    elsif params[:search]
      @tasks = Task.search(params[:search]).order("created_at DESC").page(params[:page])
    else params[:sort_with_created_at]
      @tasks = Task.order('created_at DESC').page(params[:page])
    end
  end

  def show
  end

  def new
    @task = Task.new
  end

  def edit
  end

  def create
    @task = Task.new(task_params)
    @task.user_id = current_user.id
    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_task
    @task = Task.find(params[:id])
    end

    def task_params
    params.require(:task).permit(:title, :content, :start_date, :end_date, :status,:priority, :user_id, label_ids:[])
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<div class="container">
  <%= form_with(model: task, local: true) do |form| %>
    <% if task.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

        <ul>
        <% task.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <form class="form-horizontal">
      <div class="form-group">
      <%= form.label :title %>
      <%= form.text_field :title, class:'form-control' %>
    </div>

    <div class="form-group">
      <%= form.label :content %>
      <%= form.text_area :content, class:'form-control' %>
    </div>

    <div class="form-group">
      <%= form.label :start_date %>
      <%= form.date_select :start_date, class:'form-control' %>
    </div>

    <div class="form-group">
      <%= form.label :end_date %>
      <%= form.date_select :end_date, class:'form-control' %>
    </div>


    <div class="form-group">
      <%= form.label :status %>
      <%= form.radio_button :status, 'not started' %>Not Started <%= form.radio_button :status, 'in progress' %>In Progress <%= form.radio_button :status, 'ended' %>Ended
    </div>

    <div class="form-group">
      <%= form.label :priority %>
      <%= form.radio_button :priority, 'low' %>Low <%= form.radio_button :priority, 'medium' %>Medium <%= form.radio_button :priority, 'high' %>High
    </div>
    <div class = "tables">
     <h4><%= form.label :labels %></h4><br />
      <% Label.all.each do |label| %>        
          <% if label.user.id == current_user.id %>
          <%= form.label:title, label.title %>
          <%= form.check_box :label_ids, { multiple: true, checked: label[:checked], disabled: label[:disabled], include_hidden: false }, label[:id] %>
        <% end %>
      <% end %>
    </div>
    <div class="actions">
      <%= form.submit class:'btn btn-primary btn-create'%>
    </div>
    </form>
  <% end %>
</div>

app/views/tasks/edit.html.erb
<div class="container navigation_bar">
  <h3>Editing Task</h3>
  <%= render 'form', task: @task %>
  <%= link_to 'Show', @task, class:"btn btn-secondary btn-create" %> 
  <%= link_to 'Back', tasks_path, class:"btn btn-secondary btn-create" %>
</div>

app/views/tasks/index.html.erb
<div class="container navigation_bar">
  <h3>Tasks</h3>
  <div>
  <%= search_form_for @search do |f| %>
    <form class="form-inline">
      <div class="form-group mx-sm-3 mb-2">
        <%= f.text_field :title_or_status_cont, class:"form-control btn-search",style:'margin-bottom:0px; width:40%',placeholder:'Enter a title or status you want to search: '%>
        <%= f.submit "Search", class:'btn btn-info class="btn btn-primary mb-2'%>
       </div>
    </form>    
  <%end%>
  <%= form_tag(tasks_path, :method => "get", id: "search-form") do %>
  <%= text_field_tag :search, params[:search], class:"form-control btn-search",style:'margin-bottom:0px; width:40%', placeholder: "Search by label: " %>
  <%= submit_tag "search", class:'btn btn-info class="btn btn-primary mb-2' %>
  <% end %>
  
  
  <br>
  <table class="table table-hover table-bordered">
    <thead>
      <tr>
        <th>Title</th>
        <th>Content</th>
        <th>Start date</th>
        <th>End date</th>
        <th>Created_Time</th>
        <th>Status</th>
        <th>Priority</th>
        <th>User</th>
        <th>Action</th>
      </tr>
    </thead>  
    <tbody>
      <% @tasks.each do |task| %>
        <tr>
          <% if task.user.id == current_user.id%>
            <td><%= task.title %></td>
            <td><%= task.content %></td>
            <td><%= task.start_date %></td>
            <td><%= task.end_date %></td>
            <td><%= task.created_at %></td>
            <td><%= task.status%></td>
            <td><%= task.priority %></td>
            <td><%= task.user.name %></td>
            <td><%= link_to 'Show', task, class:'btn btn-secondary btn-sm' %>
            <%= link_to 'Edit', edit_task_path(task), class:'btn btn-warning btn-sm' %>
            <%= link_to 'Destroy', task, class:'btn btn-danger btn-sm', method: :delete, data: { confirm: 'Are you sure?' } %>
            </td>
          <%end%>
        </tr>  
      <% end %>
    </tbody>
  </table>
  <br>
  <%= paginate @tasks %>
  <%= link_to 'New Task', new_task_path, class:'btn btn-primary'%>
  <br>
  <div id="links">
    <%= link_to 'Sort By created_at', tasks_path(sort_with_created_at: 'true'), class:'btn btn-secondary my_links'%>
    <%= link_to 'Sort By deadline', tasks_path(sort_with_ended_at: 'true'), class:'btn btn-secondary my_links'%>
    <%= link_to 'Sort By Priority', tasks_path(sort_with_priority: 'true'), class:'btn btn-secondary my_links'%> 
  </div>
</div>

app/views/tasks/new.html.erb
<% if logged_in? %>
   <div class="container navigation_bar">
    <h4>New Task</h4>
      <%= render 'form', task: @task %>
      <%= link_to 'Back', tasks_path, class:'btn btn-secondary' %>
   </div>
   <%else%>
       <div class="container card sign-up" style="width: 20rem; height: 30rem">
      <p>If not registed <%= link_to "Sign up", new_user_path %></p>
      <%= form_with(scope: :session, url: sessions_path, local: true) do |f| %> 
        <div class="form-group">
          <%= f.label :email, class:'font-weight-bold' %>
          <%= f.email_field :email, class:"form-control"%>
        </div>
        <div class="form-group">
          <%= f.label :password , class:'font-weight-bold'%>
          <%= f.password_field :password, class:"form-control" %>
        </div>
      <%= f.submit "Log in" ,class:"btn btn-primary font-weight-bold sign-up-btn" %>     
      <% end %>
    </div>
<%end%>

app/views/tasks/show.html.erb
<div class="card container navigation_bar">
   <h6>Task Details<h6>
  <div class="card-body">
    <p>
    <strong>Title:</strong>
    <%= @task.title %>
    </p>

    <p>
      <strong>Content:</strong>
      <%= @task.content %>
    </p>

    <p>
      <strong>Start date:</strong>
      <%= @task.start_date %>
    </p>

    <p>
      <strong>End date:</strong>
      <%= @task.end_date %>
    </p>

    <p>
      <strong>Status:</strong>
      <%= @task.status %>
    </p>
    <p>
      <strong>Priority:</strong>
      <%= @task.priority %>
    </p>
  </div>
  <p>
<p> 
<h4> Labels attached to this task</h4>
<% @task.labels.each do |label| %>
<ul>
<li class = "user-tasks">
Title:<%= label.title + '       ' %>
</li>
</ul>
<% end %>
</p>
  <div class="card-footer">
    <%= link_to 'Edit', edit_task_path(@task), class:'btn btn-warning' %> 
      <%= link_to 'Back', tasks_path, class:'btn btn-secondary' %>
  </div>
</div>