config/routes.rb
Rails.application.routes.draw do
  resources :tasks_labels
  resources :labels
  root "sessions#new"
  resources :tasks
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  namespace :admin do
    resources :users
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  validates :email, uniqueness: true, presence: true, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :password, presence: true, length: { minimum: 6 }
  has_secure_password
  has_many :tasks, dependent: :destroy
  before_validation { email.downcase! } 
  
  def self.count_admins
    @users = User.all
    @admins=0
    @users.each do |user|
      if user.admin?
        @admins += 1
      end
    end
    return @admins
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :find_param, only: [:show, :edit, :update, :destroy]
  before_action :must_be_admin
  def must_be_admin
    unless current_user.try(:admin?)
      redirect_to root_path, notice:"To go to this page, you must sign in as an admin"
    end
  end
  def new
    @user = User.new
  end

  def index
    @users = User.all
    @tasks=Task.all.page(params[:page])
  end
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        session[:user_id]= @user.id
        format.html { redirect_to admin/users_path(@user.id), notice: 'User was successfully created.' }
        format.json { render :index, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
   if @user.id == current_user.id
     redirect_to admin_users_url, notice: "You are not allowed to delete a signed user"
     @admin = User.count_admins
   elsif @admin == 1
     redirect_to admin_users_url, notice: "At least one admin must remain!"
   else
     @user.destroy
     redirect_to admin_users_url, notice: 'User was successfully destroyed.'
   end
  end
  
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to admin_users_path, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    # unless logged_in? && current_user.id == @user.id && user.admin?
    #   raise ActionController::RoutingError.new('Not Found')
    # end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password,:password_confirmation,:admin)
  end
  def find_param
    @user = User.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_param, only: [:show, :edit, :update, :destroy, :check_profile]
  def new
    @user = User.new
  end

  def index
    @users = User.all
  end

  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save 
        session[:user_id]= @user.id
        if @user.admin?
            format.html { redirect_to tasks_path, notice: 'User was successfully created'}
          elsif !@user.admin?
            format.html { redirect_to tasks_path, notice: 'User was successfully created.' }
          else
            render 'new'
        end
      end
    end
  end
  def destroy
    if @user.id == current_user.id
      redirect_to admin_users_url, notice: "You are not allowed to delete a signed user"
      @admin = User.count_admins
    elsif @admin == 1
      redirect_to admin_users_url, notice: "At least one admin must remain!"
    else
      @user.destroy
      redirect_to admin_users_url, notice: 'User was successfully destroyed.'
    end
  end

  def show  
    # unless  logged_in? && current_user.id == !@user.id
    #   raise ActionController::RoutingError.new('Not Found')      
    # end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_path, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password,:password_confirmation,:admin)
  end
  def find_param
    @user = User.find(params[:id])
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<%= render 'layouts/nav_login' %>
<div>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= form_with(model: @user, local: true) do |f| %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class:'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :email %>
      <%= f.email_field :email, class:'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :password %>
      <%= f.password_field :password, class:'form-control' %>
    </div>    
    <div class="form-group">
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, class:'form-control' %>
    </div>
    <div class="form-group">
      <%= f.check_box :admin%> Make admin
    </div>
    <%= f.submit "Create my account", class:'btn btn-primary sign-up-btn' %>
  <% end %>
  <p>If you have account <%= link_to "Login", new_session_path %><p>
</div>

app/views/admin/users/edit.html.erb
<div class="container">
    <h3>Editing User</h3>
    <%= render 'form'%>
</div>

app/views/admin/users/index.html.erb
<div class="container navigation_bar">
  <h3>All Users</h3>
    
    <table class="table table-hover table-bordered navigation_bar">
      <thead>
      <tr>
          <td>Name</td>
          <td>Email</td>
          <td>NO. of tasks</td>
          <td>Admin</td>
          <td>Action</td>
      </tr>
      </thead>   
      <tbody>
      <% @users.each do |item| %>
      <tr>
          <td><%= item.name%></td>
          <td><%= item.email%></td>
          <td><%= Task.where(user_id: item.id).count %></td>
          <td><%= item.admin %></td>
          <td>
          <%= link_to 'Details', admin_user_path(item), class:'btn btn-warning' %>
           <%= link_to 'Edit', edit_admin_user_path(item), class:'btn btn-warning btn-sm' %>
           <%= link_to 'Destroy', item, class:'btn btn-danger btn-sm', method: :delete, data: { confirm: 'Are you sure?' } %>              
          </td>
      </tr>     
      <%end%>    
      </tbody>
    </table>    
<%= link_to 'New user', new_admin_user_path, class:'btn btn-primary'%> 

<h3>All Tasks</h3>
<br>
<table class="table table-hover table-bordered">
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Created_Time</th>
      <th>Status</th>
      <th>Priority</th>
      <th>User</th>
      <th>Action</th>
    </tr>
    
  </thead>  
  <tbody>
    <% @tasks.each do |task| %>
      <tr>      
          <td><%= task.title %></td>
          <td><%= task.content %></td>
          <td><%= task.start_date %></td>
          <td><%= task.end_date %></td>
          <td><%= task.created_at %></td>
          <td><%= task.status%></td>
          <td><%= task.priority %></td>
          <td><%= task.user.name %></td>
          <td><%= link_to 'Show', task, class:'btn btn-secondary btn-sm' %>
          <%= link_to 'Edit', edit_task_path(task), class:'btn btn-warning btn-sm' %>
          <%= link_to 'Destroy', task, class:'btn btn-danger btn-sm', method: :delete, data: { confirm: 'Are you sure?' } %>
          </td>          
      </tr>  
    <% end %>
  </tbody>
</table>

<br>
<%= paginate @tasks %>
<%= link_to 'New Task', new_task_path, class:'btn btn-primary'%>
<br>
<div id="links">
  <%= link_to 'Sort By created_at', tasks_path(sort_with_created_at: 'true'), class:'btn btn-secondary my_links'%>
  <%= link_to 'Sort By deadline', tasks_path(sort_with_ended_at: 'true'), class:'btn btn-secondary my_links'%>
  <%= link_to 'Sort By Priority', tasks_path(sort_with_priority: 'true'), class:'btn btn-secondary my_links'%> 
</div>
</div>
 

app/views/admin/users/new.html.erb
<div class="container card sign-up" style="width: 20rem;"">
    <h1>New User</h1>
    <%= render 'form', user: @user %>    
</div>

app/views/admin/users/show.html.erb
<div class="container navigation_bar card">
  <div class="card-header">
    <p>Name: <%= @user.name %><p>
    <p>Email address: <%= @user.email %></p>
  </div>
  <div class="card-footer">
    <%= link_to 'Back', admin_users_path, class:'btn btn-secondary' %>
  </div>
</div>